version: "2.1"

volumes:
  state: {}
  usdata: {}

services:
  tailscale:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    restart: on-failure
    volumes:
      - state:/var/lib/tailscale
    labels:
      - io.balena.features.kernel-modules=1
    cap_add:
      - net_admin
      - net_raw
      - sys_module
    tmpfs:
      - /tmp
      - /var/run/
  upsnap:
    container_name: upsnap
    image: seriousm4x/upsnap:5
    network_mode: host
    restart: unless-stopped
    volumes:
      - usdata:/app/pb_data
    environment:
      - TZ=Europe/Bratislava
      - UPSNAP_SCAN_RANGE=192.168.1.0/24
      - UPSNAP_PING_PRIVILEGED=true
    healthcheck:
      test: curl -fs "http://localhost:8090/api/health" || exit 1
      interval: 10s
